name: Cypress e2e tests

on:
  push:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v1.16.1
      with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
      env:
          CYPRESS_baseUrl: http://localhost:8080
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: imagediffs
        path: tests/e2e/snapshots/**/__diff_output__/*.png
